### ISSUE TITLE
JPS algorithm doesn't shows shorted path when a single block of wall is placed in between start node and stop node

### ISSUE THREAD

**Issue by Abhishek1152** [deckardmehdy/deckardmehdy.github.io#1]
So, I was playing with your jump point search algorithm and I found a small bug when the wall placed in between start and stop nodes don't show the shortest path.
![Capture](https://user-images.githubusercontent.com/45914046/80791061-2506e280-8bae-11ea-9d5e-68f2fee11a49.PNG)

**Comment by deckardmehdy** [comment]
Thank you for pointing out the flaw in the jump point search algorithm, and you are correct. This is because my version of the jump point search algorithm is non-optimal. The optimal version incorporates diagonal movements; whereas my program only searches vertically and horizontally. It performs very poorly in open spaces with minimal blocks since it has to traverse around the perimeter of the board. Hope this helps you understand.
